modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

issueTrackerURL="https://github.com/RedstoneGamer123/Create-BasicAdditions/issues"

[[mods]]
  modId="create_basic_additions"
  displayName="Create: Basic Additions"
  version="${file.jarVersion}"
  
  updateJSONURL="https://github.com/RedstoneGamer123/Create-BasicAdditions/blob/forge-master/update.json"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/create-basic-additions"
  logoFile="logo.png"
  #credits="Thanks for this example mod goes to Java"
  authors="SpokenWig620933"
  description='''
  Basic additions to the Create Mod.
  '''

  [[dependencies.create_basic_additions]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,41.0.0)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.create_basic_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19.0)"
    ordering="NONE"
    side="BOTH"
    
  [[dependencies.create_basic_additions]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.g,)"
    ordering="NONE"
    side="BOTH"